{
  "openapi": "3.0.0",
  "info": {
    "title": "Usage Consumption - NETSMS - Service Usages Broadbands (MS: consumption-netsms-serviceusagesbroadbands-v1)",
    "version": "1;2024-10-01",
    "contact": {
      "name": "COE-Microsserviços",
      "email": "coe.ms@claro.com.br"
    },
    "x-claro-domains": "Usage Consumption",
    "description": "<table>   \n  <thead>  \n    <tr>\n      <th>Version</th>\n      <th>Author</th>\n      <th>Vendor</th>\n      <th>Date</th>\n      <th>Changes</th>\n    </tr>  \n  </thead>\n  <tbody>\n    <tr>\n      <td>1.0</td>\n      <td>Gabriel Eduardo Joioso</td>\n      <td>DXC Technology</td>\n      <td>2024-10-01</td>\n      <td>[Modernização SOA] - Versão inicial</td>\n    </tr>\n    </tr>\n  </tbody>\n</table>\n\n\n## Objetivo\n\nMicrosserviço responsável por consultar informações de consumo de franquia de banda larga de clientes da Claro Residencial.\n\n## Público-Alvo\n\nAté a data desta especificação os potenciais consumidores são:\n  * API - <b>residential-serviceusagesbroadbands-v1</b> - API exposta no Apigee responsável por consultar informações de consumo de franquia de banda larga de clientes da Claro Residencial.\n\n## Provedores\n\n * Bases de Dados NETSMS\n\n## Contexto em que o microsserviço se insere\nEste microsserviço está inserido no conjunto de microsserviços para a Modernização do SOA Legado Residencial que visa substituir o seguinte serviço:\n\n  * <b>ControleFranquias12V1</b> - /ativar/aprovisionamento/controlefranquias/ControleFranquias12V1 <br/>(operações: listarConsolidado e listarDetalhado)"
  },
  "security": [
    {
      "BasicAuth": []
    },
    {
      "BearerAuth": []
    },
    {
      "ApiKeyAuth": []
    },
    {
      "OAuth2": []
    }
  ],
  "paths": {
    "/netsms/serviceusages/broadbands": {
      "get": {
        "tags": [
          "Controle de Franquia (GET /netsms/serviceusages/broadbands)"
        ],
        "summary": "Realiza consulta das informações de consumo de franquia de banda larga de forma consolidada ou detalhada de um contrato.",
        "operationId": "getConsolidated",
        "parameters": [
          {
            "name": "X-Correlation-Id",
            "in": "header",
            "description": "Código UUID identificador da transação fornecido pelo consumidor da API/MS.",
            "required": false,
            "example": "b6195102-ea4f-44e8-fed5-386e4ec2a373",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "X-QueryString",
            "in": "header",
            "description": "Header query string (LGPD compliant) onde são informados os campos de consulta de franquia de banda larga de clientes Claro Residencial. \n\n\n#### CENÁRIO 01: \n<b>Consulta consolidada de informações de consumo de franquia utilizando customerContractId e operatorCode para identificação do contrato.</b>\n\n<br/>\nCampos:\n<br/>\n<font color=\"red\"><b>customerContractId</b></font>: Número do contrato<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>operatorCode</b></font>: Código identificador da operadora<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>addressableCode</b></font>: Código endereçável do equipamento<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>startDate</b></font>: Data inicial do período de consulta<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>endDate</b></font>: Data final do período de consulta<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>detailed</b></font>: Flag para indicar se as informações devem retornar detalhas.  Se <i>False</i>, retorna mês a mês; se <i>True</i>, retorna dia a dia.<font color=\"red\"><b>&#42;</b></font>\n\n<br/>\n<b>Exemplo</b>:\n\n`customerContractId=234324308&operatorCode=052&addressableCode=D86C5A4C8C8D&startDate=2024-04-01&endDate=2024-08-01&detailed=false`\n\n<br/>\n#### CENÁRIO 02: \n<b>Consulta detalhada de informações de consumo de franquia utilizando customerContractId e operatorCode para identificação do contrato.</b>\n\n<br/>\nCampos:\n<br/>\n<font color=\"red\"><b>customerContractId</b></font>: Número do contrato<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>operatorCode</b></font>: Código identificador da operadora<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>addressableCode</b></font>: Código endereçável do equipamento<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>startDate</b></font>: Data inicial do período de consulta<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>endDate</b></font>: Data final do período de consulta<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>detailed</b></font>: Flag para indicar se as informações devem retornar detalhadas. Se <i>False</i>, retorna mês a mês; se <i>True</i>, retorna dia a dia.<font color=\"red\"><b>&#42;</b></font>\n\n<br/>\n<b>Exemplo</b>:\n\n`customerContractId=234324308&operatorCode=052&addressableCode=D86C5A4C8C8D&startDate=2024-07-01&endDate=2024-08-01&detailed=true`\n\n<br/>\n#### CENÁRIO 03: \n<b>Consulta consolidada de informações de consumo de franquia utilizando customerContractId e cityId para identificação do contrato.</b>\n\n<br/>\nCampos:\n<br/>\n<font color=\"red\"><b>customerContractId</b></font>: Número do contrato<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>cityId</b></font>: Código identificador da operadora<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>addressableCode</b></font>: Código endereçável do equipamento<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>startDate</b></font>: Data inicial do período de consulta<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>endDate</b></font>: Data final do período de consulta<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>detailed</b></font>: Flag para indicar se as informações devem retornar detalhas.  Se <i>False</i>, retorna mês a mês; se <i>True</i>, retorna dia a dia.<font color=\"red\"><b>&#42;</b></font>\n<font color>\n\n<br/>\n<b>Exemplo</b>:\n\n`customerContractId=234324308&cityId=05509&addressableCode=D86C5A4C8C8D&startDate=2024-04-01&endDate=2024-08-01&detailed=false`\n\n<br/>\n#### CENÁRIO 04: \n<b>Consulta consolidada de informações de consumo de franquia utilizando smartCardNumber para identificação do contrato e cidade.</b>\n\n<br/>\nCampos:\n<br/>\n<b>customerContractId</b>: Número do contrato para identificação do contrato.\n<br/>\n<b>operatorCode</b>: Código identificador da operadora.\n<br/>\n<font color=\"red\"><b>smartCardNumber</b></font>: Número do Smart Card do equipamento.<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>addressableCode</b></font>: Código endereçável do equipamento.<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>startDate</b></font>: Data inicial do período de consulta.<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>endDate</b></font>: Data final do período de consulta.<font color=\"red\"><b>&#42;</b></font>\n<br/>\n<font color=\"red\"><b>detailed</b></font>: Flag para indicar se as informações devem retornar detalhas.  Se <i>False</i>, retorna mês a mês; se <i>True</i>, retorna dia a dia.<font color=\"red\"><b>&#42;</b></font>\n<font color>\n\n<br/>\n<b>Exemplo</b>:\n\n`smartCardNumber=0D86C5A4C8C8D&addressableCode=D86C5A4C8C8D&startDate=2024-04-01&endDate=2024-08-01&detailed=false`\n\n<br/>\n<br/>\n<br/>\nA string resultante contém campos com nome e valor separados pelo símbolo \"&\".\n",
            "required": true,
            "example": "customerContractId=234324308&operatorCode=052&addressableCode=D86C5A4C8C8D&startDate=2024-04-01&endDate=2024-08-01&detailed=false",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Business object representing the customer broadband usage.",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "$ref": "#/components/schemas/usagesBroadbandsGetConsolidatedResponse"
                    },
                    {
                      "$ref": "#/components/schemas/usagesBroadbandsGetDetailedResponse"
                    }
                  ]
                },
                "examples": {
                  "CONSOLIDATED-BROADBAND-USAGE": {
                    "value": {
                      "data": {
                        "serviceUsage": {
                          "dataAllowance": {
                            "quota": "2000"
                          },
                          "creditPools": [
                            {
                              "month": "2024-06-30T00:00:00",
                              "totalUsed": "442.78",
                              "totalContracted": "0",
                              "totalAvailable": "1557.22",
                              "totalUsagePercentage": "22.14"
                            },
                            {
                              "month": "2024-07-30T00:00:00",
                              "totalUsed": "846.64",
                              "totalContracted": "0",
                              "totalAvailable": "1153.36",
                              "totalUsagePercentage": "42.33"
                            }
                          ]
                        }
                      }
                    }
                  },
                  "DETAILED-BROADBAND-USAGE": {
                    "value": {
                      "data": {
                        "serviceUsage": {
                          "dataAllowance": {
                            "quota": "2000"
                          },
                          "creditPools": [
                            {
                              "date": "2024-08-01T00:00:00",
                              "totalUsed": "2000.00",
                              "totalContracted": "0",
                              "totalAvailable": "0.00",
                              "totalUsagePercentage": "100",
                              "notification": "Notificado 100%"
                            },
                            {
                              "date": "2024-08-02T00:00:00",
                              "totalUsed": "2400.00",
                              "totalContracted": "0",
                              "totalAvailable": "0.00",
                              "totalUsagePercentage": "120",
                              "notification": "Notificado 120%"
                            },
                            {
                              "date": "2024-08-03T00:00:00",
                              "totalUsed": "2400.00",
                              "totalContracted": "0",
                              "totalAvailable": "0.00",
                              "totalUsagePercentage": "120",
                              "notification": "Penalizado"
                            }
                          ]
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "401": {
            "$ref": "#/components/responses/401"
          },
          "403": {
            "$ref": "#/components/responses/403"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "405": {
            "$ref": "#/components/responses/405"
          },
          "406": {
            "$ref": "#/components/responses/406"
          },
          "414": {
            "$ref": "#/components/responses/414"
          },
          "422": {
            "$ref": "#/components/responses/422"
          },
          "429": {
            "$ref": "#/components/responses/429"
          },
          "451": {
            "$ref": "#/components/responses/451"
          },
          "500": {
            "$ref": "#/components/responses/500"
          },
          "503": {
            "$ref": "#/components/responses/503"
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "https://consumption-netsms-serviceusagesbroadbands-v1.dev.lpa.k8s.corp.clarobr/consumption/v1",
      "description": "Development (on-premises DC Lapa)"
    },
    {
      "url": "https://consumption-netsms-serviceusagesbroadbands-v1-sit1.hom.lpa.k8s.corp.clarobr/consumption/v1",
      "description": "Homologation SIT01 (on-premises DC Lapa)"
    },
    {
      "url": "https://consumption-netsms-serviceusagesbroadbands-v1-sit3.hom.lpa.k8s.corp.clarobr/consumption/v1",
      "description": "Homologation SIT03 (on-premises DC Lapa)"
    },
    {
      "url": "https://consumption-netsms-serviceusagesbroadbands-v1-sit4.hom.lpa.k8s.corp.clarobr/consumption/v1",
      "description": "Homologation SIT04 (on-premises DC Lapa)"
    },
    {
      "url": "https://consumption-netsms-serviceusagesbroadbands-v1-sit5.hom.lpa.k8s.corp.clarobr/consumption/v1",
      "description": "Homologation SIT05 (on-premises DC Lapa)"
    },
    {
      "url": "https://consumption-netsms-serviceusagesbroadbands-v1-sit6.hom.lpa.k8s.corp.clarobr/consumption/v1",
      "description": "Homologation SIT06 (on-premises DC Lapa)"
    },
    {
      "url": "https://consumption-netsms-serviceusagesbroadbands-v1-sit7.hom.lpa.k8s.corp.clarobr/consumption/v1",
      "description": "Homologation SIT07 (on-premises DC Lapa)"
    },
    {
      "url": "https://consumption-netsms-serviceusagesbroadbands-v1-crt1.hom.lpa.k8s.corp.clarobr/activation/v1",
      "description": "Homologation CRT01 (on-premises DC Lapa)"
    },
    {
      "url": "https://consumption-netsms-serviceusagesbroadbands-v1.prod.lpa.k8s.corp.clarobr/consumption/v1",
      "description": "Production (on-premises DC Lapa)"
    }
  ],
  "components": {
    "securitySchemes": {
      "BasicAuth": {
        "type": "http",
        "scheme": "basic"
      },
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer"
      },
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "X-API-Key"
      },
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/oauth2/v1/token",
            "scopes": {}
          }
        }
      }
    },
    "schemas": {
      "usagesBroadbandsGetConsolidatedResponse": {
        "description": "Root structure of a consolidated broadband service usage GET response.",
        "type": "object",
        "properties": {
          "data": {
            "type": "object",
            "properties": {
              "serviceUsage": {
                "$ref": "#/components/schemas/usagesBroadbandsConsolidatedServiceUsage"
              }
            }
          }
        },
        "required": [
          "data"
        ]
      },
      "usagesBroadbandsConsolidatedServiceUsage": {
        "description": "Business object that represents the consolidated service usage for broadband.",
        "type": "object",
        "properties": {
          "dataAllowance": {
            "$ref": "#/components/schemas/serviceUsagesBroadbandsConsolidatedDataAllowance"
          },
          "creditPools": {
            "$ref": "#/components/schemas/serviceUsagesBroadbandsConsolidatedCreditPools"
          }
        },
        "required": [
          "dataAllowance",
          "creditPools"
        ]
      },
      "serviceUsagesBroadbandsConsolidatedDataAllowance": {
        "description": "Business object representing the broadband data quota in consolidated usage.",
        "type": "object",
        "properties": {
          "quota": {
            "type": "string",
            "description": "Quota da franquia de banda larga do cliente.",
            "example": "2000"
          }
        }
      },
      "serviceUsagesBroadbandsConsolidatedCreditPools": {
        "description": "Business object representing the consolidated credit pools with usage details.",
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/serviceUsagesBroadbandsConsolidatedCreditPool"
        }
      },
      "serviceUsagesBroadbandsConsolidatedCreditPool": {
        "description": "Business Object representing a single consolidated credit pool entry.",
        "type": "object",
        "properties": {
          "month": {
            "type": "string",
            "format": "date-time",
            "description": "Mês de referência do pool de créditos.",
            "example": "2024-06-30T00:00:00"
          },
          "totalUsed": {
            "type": "string",
            "description": "Total utilizado (em GB).",
            "example": "442.78"
          },
          "totalContracted": {
            "type": "string",
            "description": "Total contratado (em GB).",
            "example": "0"
          },
          "totalAvailable": {
            "type": "string",
            "description": "Total disponível (em GB).",
            "example": "1557.22"
          },
          "totalUsagePercentage": {
            "type": "string",
            "description": "Percentual de utilização do total disponível.",
            "example": "22.14"
          }
        }
      },
      "usagesBroadbandsGetDetailedResponse": {
        "description": "Root structure of a detailed broadband service usage GET response.",
        "type": "object",
        "properties": {
          "data": {
            "type": "object",
            "properties": {
              "serviceUsage": {
                "$ref": "#/components/schemas/usagesBroadbandsDetailedServiceUsage"
              }
            }
          }
        },
        "required": [
          "data"
        ]
      },
      "usagesBroadbandsDetailedServiceUsage": {
        "description": "Business object that represents the detailed service usage for broadband.",
        "type": "object",
        "properties": {
          "dataAllowance": {
            "$ref": "#/components/schemas/serviceUsagesBroadbandsDetailedDataAllowance"
          },
          "creditPools": {
            "$ref": "#/components/schemas/serviceUsagesBroadbandsDetailedCreditPools"
          }
        },
        "required": [
          "dataAllowance",
          "creditPools"
        ]
      },
      "serviceUsagesBroadbandsDetailedDataAllowance": {
        "description": "Business object representing the broadband data quota in detailed usage.",
        "type": "object",
        "properties": {
          "quota": {
            "type": "string",
            "description": "Quota da franquia de banda larga do cliente.",
            "example": "2000"
          }
        }
      },
      "serviceUsagesBroadbandsDetailedCreditPools": {
        "description": "Business object representing the detailed credit pools with usage details.",
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/serviceUsagesBroadbandsDetailedCreditPool"
        }
      },
      "serviceUsagesBroadbandsDetailedCreditPool": {
        "description": "Business object representing a single detailed credit pool entry.",
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date-time",
            "description": "Dia de referência do pool de créditos.",
            "example": "2024-08-02T00:00:00"
          },
          "totalUsed": {
            "type": "string",
            "description": "Total utilizado (em GB).",
            "example": "100.00"
          },
          "totalContracted": {
            "type": "string",
            "description": "Total contratado (em GB).",
            "example": "0"
          },
          "totalAvailable": {
            "type": "string",
            "description": "Total disponível (em GB).",
            "example": "1900.82"
          },
          "totalUsagePercentage": {
            "type": "string",
            "description": "Percentual de utilização do total disponível.",
            "example": "5.00"
          },
          "notification": {
            "type": "string",
            "description": "Notificação (pode ser vazia).",
            "example": "Notificado 50%"
          }
        }
      },
      "errorGeneric": {
        "description": "Object returned when an error occurs (4xx/5xx)",
        "type": "object",
        "required": [
          "error"
        ],
        "properties": {
          "error": {
            "type": "object",
            "properties": {
              "httpCode": {
                "type": "string",
                "description": "HTTP error code"
              },
              "errorCode": {
                "type": "string",
                "description": "Internal API error code. Ex.: API-3566. This code can be used by\nconsumer to map its error message."
              },
              "message": {
                "type": "string",
                "description": "Error Message."
              },
              "detailedMessage": {
                "type": "string",
                "description": "Detailed error message."
              },
              "link": {
                "type": "object",
                "description": "Object containing page link to errors detailed documentation on\nAPI Portal.",
                "properties": {
                  "rel": {
                    "type": "string",
                    "enum": [
                      "related"
                    ],
                    "description": "To reference the API portal error page is used the “related”\nsemantics in this scenario."
                  },
                  "href": {
                    "type": "string",
                    "description": "Resource URL"
                  }
                }
              }
            }
          }
        }
      }
    },
    "responses": {
      "400": {
        "description": "Bad Request",
        "content": {
          "application/json": {
            "examples": {
              "API-USAGESBROADBANDS-001": {
                "value": {
                  "error": {
                    "httpCode": "400",
                    "errorCode": "API-SERVICEUSAGESBROADBANDS-400",
                    "message": "Bad Request",
                    "detailedMessage": "Required some parameters not found: 'customerContractId' or 'smartCardNumber'. It is mandatory to fill only one of the two fields informed.",
                    "link": {
                      "rel": "related",
                      "href": "https://api.claro.com.br/docs"
                    }
                  }
                }
              },
              "API-USAGESBROADBANDS-002": {
                "value": {
                  "error": {
                    "httpCode": "400",
                    "errorCode": "API-SERVICEUSAGESBROADBANDS-400",
                    "message": "Bad Request",
                    "detailedMessage": "For requests that uses 'customerContractId', it is necessary to enter the 'cityId' or 'operatorCode'. It is mandatory to fill only one of the two fields informed.",
                    "link": {
                      "rel": "related",
                      "href": "https://api.claro.com.br/docs"
                    }
                  }
                }
              },
              "API-USAGESBROADBANDS-003": {
                "value": {
                  "error": {
                    "httpCode": "400",
                    "errorCode": "API-SERVICEUSAGESBROADBANDS-400",
                    "message": "Bad Request",
                    "detailedMessage": "Format data field informed is no valid. Only numbers are valid. Please check the documentation out to know the correct way to fill in the fields.",
                    "link": {
                      "rel": "related",
                      "href": "https://api.claro.com.br/docs"
                    }
                  }
                }
              },
              "API-USAGESBROADBANDS-004": {
                "value": {
                  "error": {
                    "httpCode": "400",
                    "errorCode": "API-SERVICEUSAGESBROADBANDS-400",
                    "message": "Bad Request",
                    "detailedMessage": "Required parameters not found: 'addressableCode', 'startDate', 'endDate', or the boolean flag 'detailed'. It is mandatory to fill all of the fields informed.",
                    "link": {
                      "rel": "related",
                      "href": "https://api.claro.com.br/docs"
                    }
                  }
                }
              },
              "API-USAGESBROADBANDS-005": {
                "value": {
                  "error": {
                    "httpCode": "400",
                    "errorCode": "API-SERVICEUSAGESBROADBANDS-400",
                    "message": "Bad Request",
                    "detailedMessage": "The xquery string informed is out of standard. Please check the documentation out to know the correct way to fill in the fields.",
                    "link": {
                      "rel": "related",
                      "href": "https://api.claro.com.br/docs"
                    }
                  }
                }
              },
              "API-USAGESBROADBANDS-006": {
                "value": {
                  "error": {
                    "httpCode": "400",
                    "errorCode": "API-SERVICEUSAGESBROADBANDS-400",
                    "message": "Bad Request",
                    "detailedMessage": "The endDate field contains a date earlier than the startDate. Please enter an endDate later than the startDate.",
                    "link": {
                      "rel": "related",
                      "href": "https://api.claro.com.br/docs"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "401": {
        "description": "Unauthorized",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/errorGeneric"
            },
            "example": {
              "error": {
                "httpCode": "401",
                "errorCode": "API-SERVICEUSAGESBROADBANDS-401",
                "message": "Unauthorized",
                "detailedMessage": "Unauthorized user.",
                "link": {
                  "rel": "related",
                  "href": "https://api.claro.com.br/docs"
                }
              }
            }
          }
        }
      },
      "403": {
        "description": "Forbidden",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/errorGeneric"
            },
            "example": {
              "error": {
                "httpCode": "403",
                "errorCode": "API-SERVICEUSAGESBROADBANDS-403",
                "message": "Forbidden",
                "detailedMessage": "Client authorization failed.",
                "link": {
                  "rel": "related",
                  "href": "https://api.claro.com.br/docs"
                }
              }
            }
          }
        }
      },
      "404": {
        "description": "Not Found",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/errorGeneric"
            },
            "example": {
              "error": {
                "httpCode": "404",
                "errorCode": "API-SERVICEUSAGESBROADBANDS-404",
                "message": "Not Found",
                "detailedMessage": "Resource not found.",
                "link": {
                  "rel": "related",
                  "href": "https://api.claro.com.br/docs"
                }
              }
            }
          }
        }
      },
      "405": {
        "description": "Method Not Allowed",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/errorGeneric"
            },
            "example": {
              "error": {
                "httpCode": "405",
                "errorCode": "API-SERVICEUSAGESBROADBANDS-405",
                "message": "Method Not Allowed",
                "detailedMessage": "Unavailable HTTP method.",
                "link": {
                  "rel": "related",
                  "href": "https://api.claro.com.br/docs"
                }
              }
            }
          }
        }
      },
      "406": {
        "description": "Not Acceptable",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/errorGeneric"
            },
            "example": {
              "error": {
                "httpCode": "406",
                "errorCode": "API-SERVICEUSAGESBROADBANDS-406",
                "message": "Request Not Acceptable",
                "detailedMessage": "Requested content type not acceptable.",
                "link": {
                  "rel": "related",
                  "href": "https://api.claro.com.br/docs"
                }
              }
            }
          }
        }
      },
      "414": {
        "description": "Request-URI Too Large",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/errorGeneric"
            },
            "example": {
              "error": {
                "httpCode": "414",
                "errorCode": "API-SERVICEUSAGESBROADBANDS-414",
                "message": "Request-URI Too Large",
                "detailedMessage": "URI limits check failed.",
                "link": {
                  "rel": "related",
                  "href": "https://api.claro.com.br/docs"
                }
              }
            }
          }
        }
      },
      "415": {
        "description": "Unsupported Media Type",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/errorGeneric"
            },
            "example": {
              "error": {
                "httpCode": "415",
                "errorCode": "API-SERVICEUSAGESBROADBANDS-415",
                "message": "Unsupported Media Type",
                "detailedMessage": "Unsupported Media Type.",
                "link": {
                  "rel": "related",
                  "href": "https://api.claro.com.br/docs"
                }
              }
            }
          }
        }
      },
      "422": {
        "description": "Unprocessable Entity",
        "content": {
          "application/json": {
            "examples": {
              "API-USAGESBROADBANDS-001": {
                "value": {
                  "error": {
                    "httpCode": "422",
                    "errorCode": "API-SERVICEUSAGESBROADBANDS-007",
                    "message": "Unprocessable Entity",
                    "detailedMessage": "CityID not found. The query did not return any CityID for the provided OperatorCode.",
                    "link": {
                      "rel": "related",
                      "href": "https://api.claro.com.br/docs"
                    }
                  }
                }
              },
              "API-USAGESBROADBANDS-002": {
                "value": {
                  "error": {
                    "httpCode": "422",
                    "errorCode": "API-SERVICEUSAGESBROADBANDS-008",
                    "message": "Unprocessable Entity",
                    "detailedMessage": "Customer data not found. The customer information could not be retrieved from database.",
                    "link": {
                      "rel": "related",
                      "href": "https://api.claro.com.br/docs"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "429": {
        "description": "Too Many Requests",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/errorGeneric"
            },
            "example": {
              "error": {
                "httpCode": "429",
                "errorCode": "API-SERVICEUSAGESBROADBANDS-429",
                "message": "Too Many Requests",
                "detailedMessage": "Consumer requests exceeded policies.",
                "link": {
                  "rel": "related",
                  "href": "https://api.claro.com.br/docs"
                }
              }
            }
          }
        }
      },
      "451": {
        "description": "Unavailable For Legal Reasons",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/errorGeneric"
            },
            "example": {
              "error": {
                "httpCode": "451",
                "errorCode": "API-SERVICEUSAGESBROADBANDS-451",
                "message": "Unavailable For Legal Reasons",
                "detailedMessage": "Unavailable For Legal Reasons.",
                "link": {
                  "rel": "related",
                  "href": "https://api.claro.com.br/docs"
                }
              }
            }
          }
        }
      },
      "500": {
        "description": "Internal Server Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/errorGeneric"
            },
            "example": {
              "error": {
                "httpCode": "500",
                "errorCode": "API-SERVICEUSAGESBROADBANDS-500",
                "message": "Internal Server Error",
                "detailedMessage": "Internal Server Error.",
                "link": {
                  "rel": "related",
                  "href": "https://api.claro.com.br/docs"
                }
              }
            }
          }
        }
      },
      "503": {
        "description": "Service unavailable",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/errorGeneric"
            },
            "example": {
              "error": {
                "httpCode": "503",
                "errorCode": "API-SERVICEUSAGESBROADBANDS-503",
                "message": "Service Unavailable",
                "detailedMessage": "Service Unavailable.",
                "link": {
                  "rel": "related",
                  "href": "https://api.claro.com.br/docs"
                }
              }
            }
          }
        }
      }
    }
  }
}